# Generated by Django 5.2.4 on 2025-07-23 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='rate',
        ),
        migrations.AddField(
            model_name='item',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='number_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mailcollector',
            name='ai_response',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='barista',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='barista',
            name='experience_years',
            field=models.PositiveIntegerField(),
        ),
    ]
