# Generated by Django 5.2.4 on 2025-07-23 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop_app', '0002_remove_item_rate_item_avg_rating_item_number_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='active',
        ),
    ]
