# Generated by Django 5.2.4 on 2025-07-24 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop_app', '0003_remove_review_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rate',
            new_name='rating',
        ),
    ]
