# Generated by Django 5.2.4 on 2025-07-24 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop_app', '0004_rename_rate_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='rate',
        ),
    ]
