# Generated by Django 5.2.4 on 2025-07-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop_app', '0007_remove_category_item_item_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='item',
            name='sizes',
        ),
        migrations.AddField(
            model_name='item',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='items', to='coffeeshop_app.size'),
        ),
    ]
