# Generated by Django 5.2.4 on 2025-07-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop_app', '0009_ingredient_remove_item_ingredients_item_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='related_items',
            field=models.ManyToManyField(blank=True, related_name='items', to='coffeeshop_app.item'),
        ),
    ]
