# Generated by Django 5.2.4 on 2025-07-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop_app', '0010_alter_item_related_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='related_items',
            field=models.ManyToManyField(blank=True, to='coffeeshop_app.item'),
        ),
    ]
