# Generated by Django 5.2.4 on 2025-08-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop_app', '0011_alter_item_related_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_story', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='about/')),
                ('coffee_journy', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('map_url', models.URLField(blank=True, max_length=500)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
