# Generated by Django 5.2.4 on 2025-09-02 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop_app', '0012_about_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barista',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='info_arr',
        ),
        migrations.CreateModel(
            name='FarmInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='farm_info/')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_arr', to='coffeeshop_app.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('barista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nationalities', to='coffeeshop_app.barista')),
            ],
        ),
    ]
