# Generated by Django 5.2.4 on 2025-09-03 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop_app', '0013_remove_barista_nationality_remove_farm_info_arr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='coffee_journy',
        ),
        migrations.AddField(
            model_name='contactus',
            name='location',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CoffeeJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='coffee_journey/')),
                ('description', models.TextField()),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coffee_journey', to='coffeeshop_app.about')),
            ],
        ),
    ]
