# Generated by Django 5.2.4 on 2025-09-03 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop_app', '0014_remove_about_coffee_journy_contactus_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeejourney',
            name='photo',
        ),
        migrations.AddField(
            model_name='coffeejourney',
            name='title',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nationality',
            name='barista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nationality', to='coffeeshop_app.barista'),
        ),
    ]
