# Generated by Django 5.2.4 on 2025-09-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop_app', '0016_barista_nationality_code_barista_nationality_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_user',
        ),
        migrations.AddField(
            model_name='review',
            name='user_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('item', 'email'), name='unique_review_per_email_item'),
        ),
    ]
