# Generated by Django 5.2.4 on 2025-09-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop_app', '0017_remove_review_review_user_review_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='our_story',
            field=models.TextField(),
        ),
    ]
