# Generated by Django 5.2.4 on 2025-09-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop_app', '0018_alter_about_our_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barista',
            name='nationality_code',
            field=models.CharField(max_length=50),
        ),
    ]
